const {rm, cp, mkdir, exec, echo, pwd, cd} = require('shelljs')
const chalk = require('chalk')

// console.log(chalk.green('1.clear'))
// rm('-rf', '/Users/jiabinbin/myself/blog/public')
// console.log('do build')
console.log(`pwd: ${pwd()}`)
exec('cd blog')
console.log(`pwd: ${pwd()}`)
exec('yarn build')
// console.log('do zip')
// exec('zip -q -r -o "public.zip" "/public"')
// exec('cd ..')
// rm('-rf', '/Users/jiabinbin/myself/blog/public.zip')
// console.log(`pwd: ${pwd()}`)
// console.log('222')
// exec('zip -q -r -o public.zip public')
exec('./hooks/deploy.sh')