# Todo: mode: ligh | dark | Todo: auto
mode: light

# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
# color
colors:
  primary: "#0078E7"
  # primary: "#6200ee"
  selection_bg: "#8e71c1"

# Favicon
# ---------------
favicon: /favicon.ico

# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------

# Posts / Categories / Tags in sidebar.
sidebar:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-1.jpg

site_state: true

# Social Links.
social:
  RSS:
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  QQ:
    # https://isux.tencent.com/wp-content/uploads/2016/05/20160512101222609.pdf
    link: https://wpa.qq.com/msgrd?v=3&uin=425605679&site=qq&menu=yes
    icon: icon-qq-line
    color: "#12B7F5"
  GitHub:
    link: https://github.com/jiabinbin
    icon: icon-github-line
    color: "#181717"
  E-Mail:
    link: mailto:425605679@qq.com
    icon: icon-mail-line
    color: "#8E71C1"
#  微博:
#    link: https://weibo.com/jizhideyunyoujun
#    icon: icon-weibo-line
#    color: "#E6162D"
#  豆瓣:
#    link: https://www.douban.com/people/yunyoujun/
#    icon: icon-douban-line
#    color: "#007722"
  网易云音乐:
    link: https://music.163.com/#/user/home?id=124588572
    icon: icon-netease-cloud-music-line
    color: "#C10D0C"
#  知乎:
#    link: https://www.zhihu.com/people/yunyoujun/
#    icon: icon-zhihu-line
#    color: "#0084FF"
#  哔哩哔哩动画:
#    link: https://space.bilibili.com/1579790
#    icon: icon-bilibili-line
#    color: "#FF8EB3"
#  POPI:
#    link: https://www.popiask.cn/elpsycn
#    icon: icon-questionnaire-line
#    color: "#525252"
#  微信公众号:
#    link: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/about/white-qrcode-and-search.jpg
#    icon: icon-wechat-2-line
#    color: "#1AAD19"
  # bangumi: https://bangumi.tv/user/yunyoujun || television
  # pixiv: https://pixiv.me/yunyoujun || paint-brush
  # Google: https://plus.google.com/yourname || google
  # Twitter: https://twitter.com/yunyoujun || twitter
  # FB Page: https://www.facebook.com/yourname || facebook
  # StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  # YouTube: https://youtube.com/yourname || youtube
  # Instagram: https://instagram.com/yourname || instagram
  # Skype: skype:yourname?call|chat || skype

# Extra links
pages:
  我的小伙伴们:
    url: /links/
    icon: icon-men-line
    color: dodgerblue
  喜欢的女孩子:
    url: /girls/
    icon: icon-women-line
    color: hotpink
# pages
# -------
# friend -- jobin
#anonymous_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/avatar/none.jpg

girls:
  enable: false

banner:
  title: 落梅听风雪
  src: /js/ui/banner.js

# Sidebar Avatar
avatar:
  enable: true
  url: /photo.jpg
  # If true, the avatar would be dispalyed in circle.
  rounded: true
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1

# main menu navigation
menu:
  home:
    path: /
    icon: icon-home-4-line
  archives:
    path: /archives
    icon: icon-archive-line
  tags:
    path: /tags
    icon: icon-price-tag-3-line
  categories:
    path: /categories
    icon: icon-folder-2-line
  about:
    path: /about/
    icon: icon-information-line

# archive
archive:
  last_word: 没有更多的黑历史了_(:з」∠)_

# link
# -------
preload:
  style:
    - /css/hexo-theme-yun.css
  script:
    - /js/yun-boot.js
    - /js/utils.js
    - /js/hexo-theme-yun.js

prefetch:
  style:
    - /css/prism.css
  script:
    - /js/toc.js

dns_prefetch:
#  - https://cos.yunyoujun.cn
  - https://yuexiaoya.info

# do more(TCP handshake...) than dns-fetch
preconnect:
  - https://cdn.jsdelivr.net

# stylesheets loaded in the <head>
css:
  - /css/hexo-theme-yun.css

# scripts loaded in the end of the body
js:
  - /js/yun-boot.js
  - /js/utils.js
  - /js/hexo-theme-yun.js

# custom your assets in head
head:
  css:
  js:
    base:
    async:
    defer:

# cdn for third-party library (always include)
cdn:
  # you need change it to yourself
  css:
  # font
  # font: https://fonts.googleapis.com/css?family=Open+Sans:300&display=swap
  # font: https://fonts.loli.net/css?family=Montserrat
  # icon
  # material-design-icons: https://fonts.googleapis.com/icon?family=Material+Icons+Outlined
  # markdown
  # github-markdown-css: https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/3.0.1/github-markdown.min.css
  # star-markdown-css: https://cdn.jsdelivr.net/npm/star-markdown-css/dist/planet/planet-markdown.min.css
  # blood-markdown-css: https://cdn.jsdelivr.net/npm/star-markdown-css/dist/blood/blood-common.min.css
  js:
    base:
    async:
      iconfont: //at.alicdn.com/t/font_1140697_asgm6pccckc.js
    defer:
      scrollreveal: https://cdn.jsdelivr.net/npm/scrollreveal/dist/scrollreveal.min.js

# cdn for third-party library (alternative include)
vendors:
  algolia_search: https://cdn.jsdelivr.net/npm/algoliasearch@4/dist/algoliasearch-lite.umd.js
  instant_search: https://cdn.jsdelivr.net/npm/instantsearch.js@4/dist/instantsearch.production.min.js
  anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
  valine_js: https://cdn.jsdelivr.net/npm/valine/dist/Valine.min.js
  fireworks: /js/ui/fireworks.js
  rymd: /js/ui/rymd.js
  search: /js/search/index.js
  toc: /js/toc.js

# UI
fireworks: true
rymd: false

bg_image:
  enable: true
  url: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-0.jpg # recomend image related to your mode
  blur: 30px

# Reward (Donate)
reward_settings:
  # If true, reward would be displayed in every article by default.
  # You can show or hide reward in a specific article throuth `reward: true | false` in Front Matter.
  enable: true
#  url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  url: https://github.com/jiabinbin/blog/issues
  #comment: Donate comment here
reward:
  enable: false
  alipay:
    path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/alipay-qrcode.jpg
    color: "#00A3EE"
    icon: icon-alipay-line
  qq:
    path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/qqpay-qrcode.png
    color: "#12B7F5"
    icon: icon-qq-line
  wechat-pay:
    path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/wechatpay-qrcode.jpg
    color: "#2DC100"
    icon: icon-wechat-pay-line
  # paypal:
  #   link: https://paypal.com
  #   path: https://www.paypalobjects.com/images/shared/paypal-logo-129x32.svg
  #   color: "#2D70B5"
  #   icon: icon-paypal-line

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.fr, deed.de, etc.
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true

# AddThis Share, See: https://www.addthis.com
# Go to https://www.addthis.com/dashboard to customize your tools.
# add_this_id:

# Post edit
# Dependencies: https://github.com/hexojs/hexo-deployer-git
post_edit:
  enable: false
  url: https://github.com/user-name/repo-name/tree/branch-name/subdirectory-name # Link for view source.

# Footer Settings
# ---------------
footer:
  since: 2019

  # Icon between year and copyright info.
  icon:
    # `heart` is recommended with animation in red (#ff0000).
    name: icon-cloud-line
    # If you want to animate the icon, set it to true.
    animated: true
    # Change the color of icon, using Hex Code.
    color: "#0078E7"

  powered:
    # Hexo link (Powered by Hexo).
    enable: true
    # Version info of Hexo after Hexo link (vX.X.X).
    version: true

  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # http://www.beian.miit.gov.cn
  beian:
    enable: false
    # icp: 苏ICP备xxxxxxxx号

  # Any custom text can be defined here.
  # custom_text: Hosted by <a href="https://pages.coding.me" rel="noopener" target="_blank">Coding Pages</a>

# Post meta display settings
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true

# third party
# ----------------

# say something
# https://say.elpsy.cn
say:
  enable: true
  # api: https://say.elpsy.cn/sentences.json
  # if api is not exist, will use local sentences
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # src is the script
  src: /js/say.js

# you can new JSON file in your blog root folder
# example: source/data/sentences.json
# then set say.api: /data/sentences.json
# https://say.elpsy.cn
# [
#   {
#     "content": "Hello, World!",
#     "author": "Brian Kernighan",
#     "from": "The C Programming Language"
#   },
#   {
#     "content": "我们一日日度过的所谓日常，实际上可能是接连不断的奇迹。",
#     "from": "日常"
#   },
#   {
#     "content": "是啊，我所爱的，即非群星，也非银河。",
#     "author": "云游君",
#     "from": "yunyoujun.cn"
#   },
#   {
#     "content": "隐约雷鸣 阴霾天空 但盼风雨来 能留你在此",
#     "from": "万叶集·雷神短歌"
#   }
# ]

# Comments
# -------
comment:
  enable: true
  tips:
    - 若您无 GitHub 账号，可直接在下方匿名评论。
    - 若您想及时得到回复提醒，建议跳转 GitHub Issues 评论。
    - 若没有本文 Issue，您可以使用 Comment 模版新建。

# GitHub Issues Link Button
# https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests
github_issues:
  enable: true
  username: jiabinbin
  repository: blog
  filters: is:issue

# Valine
# You can get your appid and appkey from https://leancloud.cn
# More info available at https://valine.js.org
valine:
  enable: false
  appId: # your leancloud application appid
  appKey: # your leancloud application appkey
  serverURLs:
  notify: false # mail notifier, See: https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: # gravatar style
  meta: nick,mail,link # custom comment header
  pageSize: 10 # pagination size
  visitor: true

# Show Views / Visitors of the website / page with busuanzi.
# Get more information on http://ibruce.info/2015/04/04/busuanzi
busuanzi:
  enable: false
  site_uv: true
  site_uv_icon: icon-user-line
  site_pv: true
  site_pv_icon: icon-eye-line
  page_pv: true
  page_pv_icon: icon-eye-line

# Post wordcount display settings
# Dependencies: https://github.com/theme-next/hexo-symbols-count-time
symbols_count_time:
  item_text_post: true
  item_text_total: true
  awl: 2
  wpm: 275

# search
search:
  bg_image: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/bg/stars-timing-2.jpg

engine_search:
  enable: true
  href: "https://www.google.com/search?q=site:"
  domain: yuexiaoya.info

# https://github.com/wzpan/hexo-generator-search
local_search:
  enable: false
  src: /js/search/local-search.js

# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  src: /js/search/algolia-search.js
  hits:
    per_page: 8 # the number of search results per page

# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  client: ca-pub-2245427233262012

# Analysis
# ---------------
google_analytics:
  enable: false
  id: UA-XXXXXXXXX-X
